include("../5_LinearizationFunctions/generated_fcns/prepare_linearization_generated.jl")
include("../5_LinearizationFunctions/FSYS.jl")
include("../5_LinearizationFunctions/generated_fcns/FSYS_agg_generated.jl")
include("../5_LinearizationFunctions/SGU.jl")
include("../5_LinearizationFunctions/SGU_estim.jl")
include("../5_LinearizationFunctions/SolveDiffEq.jl")
include("../5_LinearizationFunctions/compute_reduction.jl")
include("../5_LinearizationFunctions/Shuffle.jl")
include("../5_LinearizationFunctions/compare_2_linearizations.jl")

