include("NumericalBasics/BrentsMethod.jl")
include("NumericalBasics/LinInterpols.jl")
include("NumericalBasics/LocateFcn.jl")
include("NumericalBasics/GCintegration.jl")
include("NumericalBasics/DCT.jl")
include("NumericalBasics/FastRoot.jl")
include("NumericalBasics/MarkovChain.jl")
include("NumericalBasics/MacroUtils.jl")
